apiVersion: v1
kind: Pod
metadata:
  name: queue
spec:
  containers:
  - name: queue
    image: queue
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8080
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "1"